#ifndef LOCI_COMMANDBUFFER_H
#define LOCI_COMMANDBUFFER_H

#include "loci_commandPool.h"

VkCommandBuffer loci_buildVkCommandBuffer;
VkCommandBuffer loci_animationUpdateVkCommandBuffer;
VkCommandBuffer loci_bottomAccelerationUpdateVkCommandBuffer;
VkCommandBuffer loci_topAccelerationUpdateVkCommandBuffer;
VkCommandBuffer loci_drawVkCommandBuffer;

void loci_createCommandBuffer(VkCommandBuffer* pCommandBuffer);
void loci_destroyCommandBuffer(VkCommandBuffer* pCommandBuffer);

void loci_beginCommand(VkCommandBuffer commandBuffer);
void loci_endCommand(VkCommandBuffer commandBuffer);

#endif