#ifndef LOCI_PHYSICALDEVICE_H
#define LOCI_PHYSICALDEVICE_H

#include "loci_surface.h"

//PhysicalDevice Info
uint32_t loci_queueFamilyIndex;
VkSurfaceFormatKHR loci_vkSurfaceFormatKHR;
VkPresentModeKHR loci_vkPresentModeKHR;
VkExtent2D loci_vkExtent2D;
VkPhysicalDeviceFeatures loci_vkPhysicalDeviceFeatures;
VkPhysicalDeviceProperties loci_vkPhysicalDeviceProperties;
VkPhysicalDeviceRayTracingPipelinePropertiesKHR loci_vkPhysicalDeviceRayTracingPipelinePropertiesKHR;
VkPhysicalDeviceMemoryProperties loci_vkPhysicalDeviceMemoryProperties;
VkSurfaceCapabilitiesKHR loci_vkSurfaceCapabilitiesKHR;

//PhysicalDevice
VkPhysicalDevice loci_vkPhysicalDevice;

void loci_pickPhysicalDevice();
uint32_t loci_findMemoryType
(uint32_t typeFilter, VkMemoryPropertyFlags properties);

#endif