#ifndef LOCI_PHYSICALDEVICE_H
#define LOCI_PHYSICALDEVICE_H

#include "loci_surface.h"

//PhysicalDevice Info
extern uint32_t loci_queueFamilyIndex;
extern VkSurfaceFormatKHR loci_vkSurfaceFormatKHR;
extern VkPresentModeKHR loci_vkPresentModeKHR;
extern VkExtent2D loci_vkExtent2D;
extern VkPhysicalDeviceFeatures loci_vkPhysicalDeviceFeatures;
extern VkPhysicalDeviceProperties loci_vkPhysicalDeviceProperties;
extern VkPhysicalDeviceRayTracingPipelinePropertiesKHR loci_vkPhysicalDeviceRayTracingPipelinePropertiesKHR;
extern VkPhysicalDeviceMemoryProperties loci_vkPhysicalDeviceMemoryProperties;
extern VkSurfaceCapabilitiesKHR loci_vkSurfaceCapabilitiesKHR;

//PhysicalDevice
extern VkPhysicalDevice loci_vkPhysicalDevice;

void loci_pickPhysicalDevice();
uint32_t loci_findMemoryType
(uint32_t typeFilter, VkMemoryPropertyFlags properties);

#endif